<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="actions/**/*.md" />
    <EmbeddedResource Include="terms/**/*.md" />
    <EmbeddedResource Include="gitignore/**/*.gitignore" />
  </ItemGroup>

</Project>
